name: ed
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  fractal:
    path: '../../pub/fractal'
  app_fractal:
    path: '../../pub/app_fractal'
  signed_fractal:
    path: '../../pub/signed_fractal'
  fractal_base:
    path: '../../pub/fractal_base'
  fractal_flutter:
    path: '../../pub/fractal_flutter'
  currency_fractal:
    path: '../../pub/currency_fractal'
  color: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
